# version: "3.8"
# services:
#   testing:
#     build: .
#     tty: true
#     volumes:
#       - .:/code
#     command: npm run test -- --watch
#   serving:
#     build: .
#     volumes:
#       - .:/code
#     command: python3 -m http.server

version: '3.8'
services:
  web:
    build: .
    command: rackup
    volumes:
      - .:/code
    ports:
      - "9292:9292"
  tests:
    image: node:14
    volumes:
      - .:/code
    command: |
      npm install
      npm run test