name: tests

on: [push]

jobs:
  acceptance-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1.1.2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
    - name: Run all acceptance tests
      run: |
        bundle install
        rake run

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUBY_CONFIG_FILE: .rubocop.yml
          VALIDATE_MARKDOWN: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_HTML: false
          LINTER_RULES_PATH: ./
